#!/bin/bash
#    Meelu Copyright 2009, 2010 Lorenzo Setale
#
#    This file is part of Meelu.
#
#    Meelu is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    any later version.
#
#    Meelu is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Meelu.  If not, see <http://www.gnu.org/licenses/>.
#

python /usr/share/meelu/main.py /usr/share/meelu
